name: multibase
description: An implementation of multibase in Dart
version: 1.0.0
homepage: https://github.com/heacare/dart-multibase
repository: https://github.com/heacare/dart-multibase

environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {base_x: ^2.0.0, characters: ^1.2.1}
